# Generated by Django 4.1.5 on 2023-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
